name: Docker Build and Push

on:
  push:
    branches:
      - '**'  # This will run on all branches

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mobi.mapr-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # Get the branch name
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          
          # Set the tag based on the branch
          if [[ "$BRANCH_NAME" == "main" ]]; then
            TAG="latest"
            CONFIGURATION="production"
          else
            TAG="stage-latest"
            CONFIGURATION="stage"
          fi
          
          echo "Building for branch: $BRANCH_NAME with tag: $TAG and configuration: $CONFIGURATION"
          
          docker build --tag $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG --build-arg CONFIGURATION=$CONFIGURATION .
          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG
